list_ =[ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
 array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.


variables list:-it the denoted of the data set by any letter of digit in list format.
array_list:-NumPy arrays are much faster and have strict requirements on the homogeneity of the objects.
array are set of data that contain the data set in proper manner in list format.

In [4]:
import numpy as np 
l=[4,5,8,7,8]

In [5]:
l  #variable_list

[4, 5, 8, 7, 8]

In [7]:
arr=np.array(l) # convert variable_list into array

In [8]:
arr

array([4, 5, 8, 7, 8])

Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]  #invalide data structure
 array_list = np.array(object = list_)

it is not import in the structure array_list

Q3. Considering the following changes in the variable, array_list:
 array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Consider the below code to answer further questions:
 import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
 num_array = np.array(object = num_list)

In [14]:
num_list=[[1,2,3],[4,5,6]]

In [15]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [18]:
df=np.array(num_list)

In [19]:
df

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:
 (i)shape

(ii) size



In [3]:
import numpy as np
sz=np.random.randint(1,8,(4,3))

In [4]:
sz.size

12

In [5]:
sz.shape

(4, 3)

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]



In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])